name: 'Auto Assign'
on:
  pull_request_target:
    types: [opened, synchronize, reopened]

jobs:
  add-reviewers:
    runs-on: ubuntu-latest
    steps:
      - uses: kentaro-m/auto-assign-action@v2.0.0
        with:
          configuration-path: '.github/auto_asign_configs.yml'
