name: "Upstream Sync"

on:
    schedule:
        - cron: "0 * * * *"
    workflow_dispatch:

jobs:
    sync_latest_from_upstream:
        name: Sync latest commits from upstream repo
        runs-on: ubuntu-latest
        if: ${{ github.event.repository.name != 'AwesomeGadgets' && github.event.repository.owner != 'AnYiEE' }}
        steps:
            - name: Checkout target repo
              uses: actions/checkout@v3
            - name: Sync upstream changes
              id: sync
              uses: aormsby/Fork-Sync-With-Upstream-action@v3.4
              with:
                  target_sync_branch: master
                  target_repo_token: ${{ secrets.GITHUB_TOKEN }}
                  upstream_sync_branch: master
                  upstream_sync_repo: AnYiEE/AwesomeGadgets
            - name: Sync check
              if: failure()
              run: |
                  echo "[Error] 由于上游仓库 workflow 文件变更或无法自动合并更改，请手动 Sync Fork 一次或手动合并更改。"
                  exit 1
